package wingan.app.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_drawer{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
views.get("panel_header").vw.setTop((int)((0d / 100 * height)));
views.get("panel_header").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_header").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_header").vw.setHeight((int)((28d / 100 * height)));
views.get("img_bg_profile").vw.setTop((int)((0d / 100 * height)));
views.get("img_bg_profile").vw.setLeft((int)((0d / 100 * width)));
views.get("img_bg_profile").vw.setWidth((int)((100d / 100 * width)));
views.get("img_bg_profile").vw.setHeight((int)((28d / 100 * height)));
views.get("img_profile").vw.setTop((int)((5d / 100 * height)));
views.get("img_profile").vw.setLeft((int)((10d / 100 * width)));
views.get("img_profile").vw.setWidth((int)((23d / 100 * width)));
views.get("img_profile").vw.setHeight((int)((15d / 100 * height)));
views.get("label_load_name").vw.setTop((int)((18d / 100 * height)));
views.get("label_load_name").vw.setLeft((int)((10d / 100 * width)));
views.get("label_load_name").vw.setWidth((int)((80d / 100 * width)));
views.get("label_load_name").vw.setHeight((int)((3d / 100 * height)));
views.get("label_load_dept").vw.setTop((int)((21d / 100 * height)));
views.get("label_load_dept").vw.setLeft((int)((10d / 100 * width)));
views.get("label_load_dept").vw.setWidth((int)((80d / 100 * width)));
views.get("label_load_dept").vw.setHeight((int)((3d / 100 * height)));
views.get("label_load_position").vw.setTop((int)((23d / 100 * height)));
views.get("label_load_position").vw.setLeft((int)((10d / 100 * width)));
views.get("label_load_position").vw.setWidth((int)((80d / 100 * width)));
views.get("label_load_position").vw.setHeight((int)((3d / 100 * height)));
views.get("panel_database").vw.setTop((int)((29d / 100 * height)));
views.get("panel_database").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_database").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_database").vw.setHeight((int)((42.4d / 100 * height)));
views.get("label_title_database").vw.setTop((int)((1d / 100 * height)));
views.get("label_title_database").vw.setLeft((int)((3d / 100 * width)));
views.get("label_title_database").vw.setWidth((int)((80d / 100 * width)));
views.get("label_title_database").vw.setHeight((int)((3d / 100 * height)));
views.get("panel_product_tbl").vw.setTop((int)((6d / 100 * height)));
views.get("panel_product_tbl").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_product_tbl").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_product_tbl").vw.setHeight((int)((9d / 100 * height)));
views.get("label_product_tbl").vw.setTop((int)((1.5d / 100 * height)));
views.get("label_product_tbl").vw.setLeft((int)((5d / 100 * width)));
views.get("label_product_tbl").vw.setWidth((int)((60d / 100 * width)));
views.get("label_product_tbl").vw.setHeight((int)((4d / 100 * height)));
views.get("label_last_producttbl").vw.setTop((int)((4.5d / 100 * height)));
views.get("label_last_producttbl").vw.setLeft((int)((5d / 100 * width)));
views.get("label_last_producttbl").vw.setWidth((int)((79d / 100 * width)));
views.get("label_last_producttbl").vw.setHeight((int)((4d / 100 * height)));
views.get("button_update_producttbl").vw.setTop((int)((1d / 100 * height)));
views.get("button_update_producttbl").vw.setLeft((int)((85d / 100 * width)));
views.get("button_update_producttbl").vw.setWidth((int)((13d / 100 * width)));
views.get("button_update_producttbl").vw.setHeight((int)((7d / 100 * height)));
views.get("panel_warehouse").vw.setTop((int)((15d / 100 * height)));
views.get("panel_warehouse").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_warehouse").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_warehouse").vw.setHeight((int)((9d / 100 * height)));
views.get("label_warehouse").vw.setTop((int)((1.5d / 100 * height)));
views.get("label_warehouse").vw.setLeft((int)((5d / 100 * width)));
views.get("label_warehouse").vw.setWidth((int)((60d / 100 * width)));
views.get("label_warehouse").vw.setHeight((int)((4d / 100 * height)));
views.get("label_last_warehouse").vw.setTop((int)((4.5d / 100 * height)));
views.get("label_last_warehouse").vw.setLeft((int)((5d / 100 * width)));
views.get("label_last_warehouse").vw.setWidth((int)((79d / 100 * width)));
views.get("label_last_warehouse").vw.setHeight((int)((4d / 100 * height)));
views.get("button_update_warehouse").vw.setTop((int)((1d / 100 * height)));
views.get("button_update_warehouse").vw.setLeft((int)((85d / 100 * width)));
views.get("button_update_warehouse").vw.setWidth((int)((13d / 100 * width)));
views.get("button_update_warehouse").vw.setHeight((int)((7d / 100 * height)));
views.get("panel_principal").vw.setTop((int)((24.1d / 100 * height)));
views.get("panel_principal").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_principal").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_principal").vw.setHeight((int)((9d / 100 * height)));
views.get("label_principal").vw.setTop((int)((1.5d / 100 * height)));
views.get("label_principal").vw.setLeft((int)((5d / 100 * width)));
views.get("label_principal").vw.setWidth((int)((60d / 100 * width)));
views.get("label_principal").vw.setHeight((int)((4d / 100 * height)));
views.get("label_last_principal").vw.setTop((int)((4.5d / 100 * height)));
views.get("label_last_principal").vw.setLeft((int)((5d / 100 * width)));
views.get("label_last_principal").vw.setWidth((int)((79d / 100 * width)));
views.get("label_last_principal").vw.setHeight((int)((4d / 100 * height)));
views.get("button_update_principal").vw.setTop((int)((1d / 100 * height)));
views.get("button_update_principal").vw.setLeft((int)((85d / 100 * width)));
views.get("button_update_principal").vw.setWidth((int)((13d / 100 * width)));
views.get("button_update_principal").vw.setHeight((int)((7d / 100 * height)));
views.get("panel_expiration").vw.setTop((int)((33.2d / 100 * height)));
views.get("panel_expiration").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_expiration").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_expiration").vw.setHeight((int)((9d / 100 * height)));
views.get("label_expiration").vw.setTop((int)((1.5d / 100 * height)));
views.get("label_expiration").vw.setLeft((int)((5d / 100 * width)));
views.get("label_expiration").vw.setWidth((int)((60d / 100 * width)));
views.get("label_expiration").vw.setHeight((int)((4d / 100 * height)));
views.get("label_last_expiration").vw.setTop((int)((4.5d / 100 * height)));
views.get("label_last_expiration").vw.setLeft((int)((5d / 100 * width)));
views.get("label_last_expiration").vw.setWidth((int)((79d / 100 * width)));
views.get("label_last_expiration").vw.setHeight((int)((4d / 100 * height)));
views.get("button_update_expiration").vw.setTop((int)((1d / 100 * height)));
views.get("button_update_expiration").vw.setLeft((int)((85d / 100 * width)));
views.get("button_update_expiration").vw.setWidth((int)((13d / 100 * width)));
views.get("button_update_expiration").vw.setHeight((int)((7d / 100 * height)));
views.get("panel_extra").vw.setTop((int)((72d / 100 * height)));
views.get("panel_extra").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_extra").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_extra").vw.setHeight((int)((15.2d / 100 * height)));
views.get("label_title_extra").vw.setTop((int)((1d / 100 * height)));
views.get("label_title_extra").vw.setLeft((int)((3d / 100 * width)));
views.get("label_title_extra").vw.setWidth((int)((80d / 100 * width)));
views.get("label_title_extra").vw.setHeight((int)((3d / 100 * height)));
views.get("panel_pricecheck").vw.setTop((int)((6d / 100 * height)));
views.get("panel_pricecheck").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_pricecheck").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_pricecheck").vw.setHeight((int)((9d / 100 * height)));
views.get("label_pricecheck").vw.setTop((int)((1.5d / 100 * height)));
views.get("label_pricecheck").vw.setLeft((int)((5d / 100 * width)));
views.get("label_pricecheck").vw.setWidth((int)((60d / 100 * width)));
views.get("label_pricecheck").vw.setHeight((int)((4d / 100 * height)));
views.get("label_sub_pricecheck").vw.setTop((int)((4.5d / 100 * height)));
views.get("label_sub_pricecheck").vw.setLeft((int)((5d / 100 * width)));
views.get("label_sub_pricecheck").vw.setWidth((int)((79d / 100 * width)));
views.get("label_sub_pricecheck").vw.setHeight((int)((4d / 100 * height)));
views.get("button_pricecheck").vw.setTop((int)((1d / 100 * height)));
views.get("button_pricecheck").vw.setLeft((int)((85d / 100 * width)));
views.get("button_pricecheck").vw.setWidth((int)((13d / 100 * width)));
views.get("button_pricecheck").vw.setHeight((int)((7d / 100 * height)));
views.get("listview_menu").vw.setTop((int)((100d / 100 * height)));
views.get("listview_menu").vw.setLeft((int)((0d / 100 * width)));
views.get("listview_menu").vw.setWidth((int)((100d / 100 * width)));
views.get("listview_menu").vw.setHeight((int)((24d / 100 * height)));

}
}