package wingan.app.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_monthly2_scrollview{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("panel_invtype").vw.setTop((int)((0d / 100 * height)));
views.get("panel_invtype").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_invtype").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_invtype").vw.setHeight((int)((35d / 100 * height)));
views.get("label_invdetails").vw.setTop((int)((1.5d / 100 * height)));
views.get("label_invdetails").vw.setLeft((int)((3d / 100 * width)));
views.get("label_invdetails").vw.setWidth((int)((40d / 100 * width)));
views.get("label_invdetails").vw.setHeight((int)((5d / 100 * height)));
views.get("label_invdetail_line").vw.setTop((int)((7.5d / 100 * height)));
views.get("label_invdetail_line").vw.setLeft((int)((3d / 100 * width)));
views.get("label_invdetail_line").vw.setWidth((int)((94d / 100 * width)));
views.get("label_invdetail_line").vw.setHeight((int)((0.2d / 100 * height)));
views.get("label_invtype").vw.setTop((int)((9d / 100 * height)));
views.get("label_invtype").vw.setLeft((int)((3d / 100 * width)));
views.get("label_invtype").vw.setWidth((int)((27d / 100 * width)));
views.get("label_invtype").vw.setHeight((int)((5d / 100 * height)));
views.get("cmb_invtype").vw.setTop((int)((9d / 100 * height)));
views.get("cmb_invtype").vw.setLeft((int)((31d / 100 * width)));
views.get("cmb_invtype").vw.setWidth((int)((66d / 100 * width)));
views.get("cmb_invtype").vw.setHeight((int)((5d / 100 * height)));
views.get("label_person").vw.setTop((int)((15d / 100 * height)));
views.get("label_person").vw.setLeft((int)((3d / 100 * width)));
views.get("label_person").vw.setWidth((int)((27d / 100 * width)));
views.get("label_person").vw.setHeight((int)((5d / 100 * height)));
views.get("label_load_person1").vw.setTop((int)((15d / 100 * height)));
views.get("label_load_person1").vw.setLeft((int)((31d / 100 * width)));
views.get("label_load_person1").vw.setWidth((int)((66d / 100 * width)));
views.get("label_load_person1").vw.setHeight((int)((5d / 100 * height)));
views.get("label_load_person2").vw.setTop((int)((21d / 100 * height)));
views.get("label_load_person2").vw.setLeft((int)((31d / 100 * width)));
views.get("label_load_person2").vw.setWidth((int)((66d / 100 * width)));
views.get("label_load_person2").vw.setHeight((int)((5d / 100 * height)));
views.get("label_position").vw.setTop((int)((27d / 100 * height)));
views.get("label_position").vw.setLeft((int)((3d / 100 * width)));
views.get("label_position").vw.setWidth((int)((27d / 100 * width)));
views.get("label_position").vw.setHeight((int)((5d / 100 * height)));
views.get("cmb_position").vw.setTop((int)((27d / 100 * height)));
views.get("cmb_position").vw.setLeft((int)((31d / 100 * width)));
views.get("cmb_position").vw.setWidth((int)((66d / 100 * width)));
views.get("cmb_position").vw.setHeight((int)((5d / 100 * height)));
views.get("panel_input").vw.setTop((int)((35d / 100 * height)));
views.get("panel_input").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_input").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_input").vw.setHeight((int)((64d / 100 * height)));
views.get("label_input").vw.setTop((int)((1.5d / 100 * height)));
views.get("label_input").vw.setLeft((int)((3d / 100 * width)));
views.get("label_input").vw.setWidth((int)((40d / 100 * width)));
views.get("label_input").vw.setHeight((int)((5d / 100 * height)));
views.get("label_input_line").vw.setTop((int)((7.5d / 100 * height)));
views.get("label_input_line").vw.setLeft((int)((3d / 100 * width)));
views.get("label_input_line").vw.setWidth((int)((94d / 100 * width)));
views.get("label_input_line").vw.setHeight((int)((0.2d / 100 * height)));
views.get("label_continues").vw.setTop((int)((1d / 100 * height)));
views.get("label_continues").vw.setLeft((int)((58d / 100 * width)));
views.get("label_continues").vw.setWidth((int)((28d / 100 * width)));
views.get("label_continues").vw.setHeight((int)((5d / 100 * height)));
views.get("switch_continues").vw.setTop((int)((1.5d / 100 * height)));
views.get("switch_continues").vw.setLeft((int)((86d / 100 * width)));
views.get("switch_continues").vw.setWidth((int)((10d / 100 * width)));
views.get("switch_continues").vw.setHeight((int)((5d / 100 * height)));
views.get("label_barcode").vw.setTop((int)((9d / 100 * height)));
views.get("label_barcode").vw.setLeft((int)((3d / 100 * width)));
views.get("label_barcode").vw.setWidth((int)((20d / 100 * width)));
views.get("label_barcode").vw.setHeight((int)((5d / 100 * height)));
views.get("label_load_barcode").vw.setTop((int)((9d / 100 * height)));
views.get("label_load_barcode").vw.setLeft((int)((24d / 100 * width)));
views.get("label_load_barcode").vw.setWidth((int)((53d / 100 * width)));
views.get("label_load_barcode").vw.setHeight((int)((5d / 100 * height)));
views.get("button_manual").vw.setTop((int)((9d / 100 * height)));
views.get("button_manual").vw.setLeft((int)((78d / 100 * width)));
views.get("button_manual").vw.setWidth((int)((19d / 100 * width)));
views.get("button_manual").vw.setHeight((int)((5d / 100 * height)));
views.get("label_principal").vw.setTop((int)((16d / 100 * height)));
views.get("label_principal").vw.setLeft((int)((3d / 100 * width)));
views.get("label_principal").vw.setWidth((int)((16d / 100 * width)));
views.get("label_principal").vw.setHeight((int)((3d / 100 * height)));
views.get("label_load_principal").vw.setTop((int)((20d / 100 * height)));
views.get("label_load_principal").vw.setLeft((int)((3d / 100 * width)));
views.get("label_load_principal").vw.setWidth((int)((94d / 100 * width)));
views.get("label_load_principal").vw.setHeight((int)((6d / 100 * height)));
views.get("label_variant").vw.setTop((int)((27d / 100 * height)));
views.get("label_variant").vw.setLeft((int)((3d / 100 * width)));
views.get("label_variant").vw.setWidth((int)((14d / 100 * width)));
views.get("label_variant").vw.setHeight((int)((3d / 100 * height)));
views.get("label_load_variant").vw.setTop((int)((31d / 100 * height)));
views.get("label_load_variant").vw.setLeft((int)((3d / 100 * width)));
views.get("label_load_variant").vw.setWidth((int)((94d / 100 * width)));
views.get("label_load_variant").vw.setHeight((int)((6d / 100 * height)));
views.get("label_description").vw.setTop((int)((38d / 100 * height)));
views.get("label_description").vw.setLeft((int)((3d / 100 * width)));
views.get("label_description").vw.setWidth((int)((20d / 100 * width)));
views.get("label_description").vw.setHeight((int)((3d / 100 * height)));
views.get("label_load_description").vw.setTop((int)((42d / 100 * height)));
views.get("label_load_description").vw.setLeft((int)((3d / 100 * width)));
views.get("label_load_description").vw.setWidth((int)((94d / 100 * width)));
views.get("label_load_description").vw.setHeight((int)((6d / 100 * height)));
views.get("label_unit").vw.setTop((int)((49d / 100 * height)));
views.get("label_unit").vw.setLeft((int)((3d / 100 * width)));
views.get("label_unit").vw.setWidth((int)((10d / 100 * width)));
views.get("label_unit").vw.setHeight((int)((7d / 100 * height)));
views.get("cmb_unit").vw.setTop((int)((49d / 100 * height)));
views.get("cmb_unit").vw.setLeft((int)((14d / 100 * width)));
views.get("cmb_unit").vw.setWidth((int)((33d / 100 * width)));
views.get("cmb_unit").vw.setHeight((int)((7d / 100 * height)));
views.get("label_quantity").vw.setTop((int)((49d / 100 * height)));
views.get("label_quantity").vw.setLeft((int)((48d / 100 * width)));
views.get("label_quantity").vw.setWidth((int)((17d / 100 * width)));
views.get("label_quantity").vw.setHeight((int)((7d / 100 * height)));
views.get("edittext_quantity").vw.setTop((int)((49d / 100 * height)));
views.get("edittext_quantity").vw.setLeft((int)((66d / 100 * width)));
views.get("edittext_quantity").vw.setWidth((int)((31d / 100 * width)));
views.get("edittext_quantity").vw.setHeight((int)((7d / 100 * height)));
views.get("button_add").vw.setTop((int)((58d / 100 * height)));
views.get("button_add").vw.setLeft((int)((76d / 100 * width)));
views.get("button_add").vw.setWidth((int)((20d / 100 * width)));
views.get("button_add").vw.setHeight((int)((5d / 100 * height)));
views.get("button_clear").vw.setTop((int)((58d / 100 * height)));
views.get("button_clear").vw.setLeft((int)((54d / 100 * width)));
views.get("button_clear").vw.setWidth((int)((20d / 100 * width)));
views.get("button_clear").vw.setHeight((int)((5d / 100 * height)));

}
}