package wingan.app.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_price_check{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
views.get("actoolbarlight1").vw.setTop((int)((0d / 100 * height)));
views.get("actoolbarlight1").vw.setLeft((int)((0d / 100 * width)));
views.get("actoolbarlight1").vw.setWidth((int)((100d / 100 * width)));
views.get("actoolbarlight1").vw.setHeight((int)((8d / 100 * height)));
views.get("panel_price_checking").vw.setTop((int)((8d / 100 * height)));
views.get("panel_price_checking").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_price_checking").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_price_checking").vw.setHeight((int)((92d / 100 * height)));
views.get("label_price_type").vw.setTop((int)((1d / 100 * height)));
views.get("label_price_type").vw.setLeft((int)((3d / 100 * width)));
views.get("label_price_type").vw.setWidth((int)((27d / 100 * width)));
views.get("label_price_type").vw.setHeight((int)((5d / 100 * height)));
views.get("cmb_pricetype").vw.setTop((int)((1d / 100 * height)));
views.get("cmb_pricetype").vw.setLeft((int)((31d / 100 * width)));
views.get("cmb_pricetype").vw.setWidth((int)((66d / 100 * width)));
views.get("cmb_pricetype").vw.setHeight((int)((5d / 100 * height)));
views.get("label_variant").vw.setTop((int)((8d / 100 * height)));
views.get("label_variant").vw.setLeft((int)((3d / 100 * width)));
views.get("label_variant").vw.setWidth((int)((21d / 100 * width)));
views.get("label_variant").vw.setHeight((int)((3d / 100 * height)));
views.get("label_load_variant").vw.setTop((int)((12d / 100 * height)));
views.get("label_load_variant").vw.setLeft((int)((3d / 100 * width)));
views.get("label_load_variant").vw.setWidth((int)((94d / 100 * width)));
views.get("label_load_variant").vw.setHeight((int)((8d / 100 * height)));
views.get("label_description").vw.setTop((int)((22d / 100 * height)));
views.get("label_description").vw.setLeft((int)((3d / 100 * width)));
views.get("label_description").vw.setWidth((int)((26d / 100 * width)));
views.get("label_description").vw.setHeight((int)((3d / 100 * height)));
views.get("label_load_description").vw.setTop((int)((26d / 100 * height)));
views.get("label_load_description").vw.setLeft((int)((3d / 100 * width)));
views.get("label_load_description").vw.setWidth((int)((94d / 100 * width)));
views.get("label_load_description").vw.setHeight((int)((8d / 100 * height)));
views.get("label_per_pcs").vw.setTop((int)((36d / 100 * height)));
views.get("label_per_pcs").vw.setLeft((int)((3d / 100 * width)));
views.get("label_per_pcs").vw.setWidth((int)((17d / 100 * width)));
views.get("label_per_pcs").vw.setHeight((int)((8d / 100 * height)));
views.get("label_load_per_pcs").vw.setTop((int)((36d / 100 * height)));
views.get("label_load_per_pcs").vw.setLeft((int)((21d / 100 * width)));
views.get("label_load_per_pcs").vw.setWidth((int)((28d / 100 * width)));
views.get("label_load_per_pcs").vw.setHeight((int)((8d / 100 * height)));
views.get("label_per_case").vw.setTop((int)((36d / 100 * height)));
views.get("label_per_case").vw.setLeft((int)((51d / 100 * width)));
views.get("label_per_case").vw.setWidth((int)((17d / 100 * width)));
views.get("label_per_case").vw.setHeight((int)((8d / 100 * height)));
views.get("label_load_per_case").vw.setTop((int)((36d / 100 * height)));
views.get("label_load_per_case").vw.setLeft((int)((69d / 100 * width)));
views.get("label_load_per_case").vw.setWidth((int)((28d / 100 * width)));
views.get("label_load_per_case").vw.setHeight((int)((8d / 100 * height)));
views.get("label_per_doz").vw.setTop((int)((46d / 100 * height)));
views.get("label_per_doz").vw.setLeft((int)((3d / 100 * width)));
views.get("label_per_doz").vw.setWidth((int)((17d / 100 * width)));
views.get("label_per_doz").vw.setHeight((int)((8d / 100 * height)));
views.get("label_load_per_doz").vw.setTop((int)((46d / 100 * height)));
views.get("label_load_per_doz").vw.setLeft((int)((21d / 100 * width)));
views.get("label_load_per_doz").vw.setWidth((int)((28d / 100 * width)));
views.get("label_load_per_doz").vw.setHeight((int)((8d / 100 * height)));
views.get("label_per_box").vw.setTop((int)((46d / 100 * height)));
views.get("label_per_box").vw.setLeft((int)((51d / 100 * width)));
views.get("label_per_box").vw.setWidth((int)((17d / 100 * width)));
views.get("label_per_box").vw.setHeight((int)((8d / 100 * height)));
views.get("label_load_per_box").vw.setTop((int)((46d / 100 * height)));
views.get("label_load_per_box").vw.setLeft((int)((69d / 100 * width)));
views.get("label_load_per_box").vw.setWidth((int)((28d / 100 * width)));
views.get("label_load_per_box").vw.setHeight((int)((8d / 100 * height)));
views.get("label_per_pack").vw.setTop((int)((56d / 100 * height)));
views.get("label_per_pack").vw.setLeft((int)((3d / 100 * width)));
views.get("label_per_pack").vw.setWidth((int)((17d / 100 * width)));
views.get("label_per_pack").vw.setHeight((int)((8d / 100 * height)));
views.get("label_load_per_pack").vw.setTop((int)((56d / 100 * height)));
views.get("label_load_per_pack").vw.setLeft((int)((21d / 100 * width)));
views.get("label_load_per_pack").vw.setWidth((int)((28d / 100 * width)));
views.get("label_load_per_pack").vw.setHeight((int)((8d / 100 * height)));
views.get("label_per_bag").vw.setTop((int)((56d / 100 * height)));
views.get("label_per_bag").vw.setLeft((int)((51d / 100 * width)));
views.get("label_per_bag").vw.setWidth((int)((17d / 100 * width)));
views.get("label_per_bag").vw.setHeight((int)((8d / 100 * height)));
views.get("label_load_per_bag").vw.setTop((int)((56d / 100 * height)));
views.get("label_load_per_bag").vw.setLeft((int)((69d / 100 * width)));
views.get("label_load_per_bag").vw.setWidth((int)((28d / 100 * width)));
views.get("label_load_per_bag").vw.setHeight((int)((8d / 100 * height)));
views.get("label_unit").vw.setTop((int)((66d / 100 * height)));
views.get("label_unit").vw.setLeft((int)((3d / 100 * width)));
views.get("label_unit").vw.setWidth((int)((10d / 100 * width)));
views.get("label_unit").vw.setHeight((int)((8d / 100 * height)));
views.get("cmb_unit").vw.setTop((int)((66d / 100 * height)));
views.get("cmb_unit").vw.setLeft((int)((14d / 100 * width)));
views.get("cmb_unit").vw.setWidth((int)((33d / 100 * width)));
views.get("cmb_unit").vw.setHeight((int)((8d / 100 * height)));
views.get("label_quantity").vw.setTop((int)((66d / 100 * height)));
views.get("label_quantity").vw.setLeft((int)((48d / 100 * width)));
views.get("label_quantity").vw.setWidth((int)((17d / 100 * width)));
views.get("label_quantity").vw.setHeight((int)((8d / 100 * height)));
views.get("edittext_quantity").vw.setTop((int)((66d / 100 * height)));
views.get("edittext_quantity").vw.setLeft((int)((66d / 100 * width)));
views.get("edittext_quantity").vw.setWidth((int)((31d / 100 * width)));
views.get("edittext_quantity").vw.setHeight((int)((8d / 100 * height)));
views.get("label_totprice").vw.setTop((int)((76d / 100 * height)));
views.get("label_totprice").vw.setLeft((int)((3d / 100 * width)));
views.get("label_totprice").vw.setWidth((int)((40d / 100 * width)));
views.get("label_totprice").vw.setHeight((int)((10d / 100 * height)));
views.get("label_load_totprice").vw.setTop((int)((76d / 100 * height)));
views.get("label_load_totprice").vw.setLeft((int)((44d / 100 * width)));
views.get("label_load_totprice").vw.setWidth((int)((53d / 100 * width)));
views.get("label_load_totprice").vw.setHeight((int)((10d / 100 * height)));

}
}