package wingan.app.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_receiving{

public static void LS_general(java.util.LinkedHashMap<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
views.get("actoolbarlight1").vw.setTop((int)((0d / 100 * height)));
views.get("actoolbarlight1").vw.setLeft((int)((0d / 100 * width)));
views.get("actoolbarlight1").vw.setWidth((int)((100d / 100 * width)));
views.get("actoolbarlight1").vw.setHeight((int)((8d / 100 * height)));
views.get("panel_receiving").vw.setTop((int)((8d / 100 * height)));
views.get("panel_receiving").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_receiving").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_receiving").vw.setHeight((int)((92d / 100 * height)));
views.get("label_principal").vw.setTop((int)((1d / 100 * height)));
views.get("label_principal").vw.setLeft((int)((3d / 100 * width)));
views.get("label_principal").vw.setWidth((int)((27d / 100 * width)));
views.get("label_principal").vw.setHeight((int)((3d / 100 * height)));
views.get("cmb_principal").vw.setTop((int)((5d / 100 * height)));
views.get("cmb_principal").vw.setLeft((int)((3d / 100 * width)));
views.get("cmb_principal").vw.setWidth((int)((94d / 100 * width)));
views.get("cmb_principal").vw.setHeight((int)((6d / 100 * height)));
views.get("table_receiving").vw.setTop((int)((12d / 100 * height)));
views.get("table_receiving").vw.setLeft((int)((0d / 100 * width)));
views.get("table_receiving").vw.setWidth((int)((100d / 100 * width)));
views.get("table_receiving").vw.setHeight((int)((78d / 100 * height)));
views.get("panel_bg_po").vw.setTop((int)((0d / 100 * height)));
views.get("panel_bg_po").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_bg_po").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_bg_po").vw.setHeight((int)((100d / 100 * height)));
views.get("panel_po").vw.setTop((int)((30d / 100 * height)));
views.get("panel_po").vw.setLeft((int)((20d / 100 * width)));
views.get("panel_po").vw.setWidth((int)((60d / 100 * width)));
views.get("panel_po").vw.setHeight((int)((23d / 100 * height)));
views.get("panel_po_header").vw.setTop((int)((0d / 100 * height)));
views.get("panel_po_header").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_po_header").vw.setWidth((int)((60d / 100 * width)));
views.get("panel_po_header").vw.setHeight((int)((7d / 100 * height)));
views.get("label_po_header").vw.setTop((int)((0d / 100 * height)));
views.get("label_po_header").vw.setLeft((int)((3d / 100 * width)));
views.get("label_po_header").vw.setWidth((int)((57d / 100 * width)));
views.get("label_po_header").vw.setHeight((int)((7d / 100 * height)));
views.get("edittext_po").vw.setTop((int)((8d / 100 * height)));
views.get("edittext_po").vw.setLeft((int)((1d / 100 * width)));
views.get("edittext_po").vw.setWidth((int)((58d / 100 * width)));
views.get("edittext_po").vw.setHeight((int)((8d / 100 * height)));
views.get("button_load").vw.setTop((int)((17d / 100 * height)));
views.get("button_load").vw.setLeft((int)((43d / 100 * width)));
views.get("button_load").vw.setWidth((int)((16d / 100 * width)));
views.get("button_load").vw.setHeight((int)((5d / 100 * height)));
views.get("button_cancel").vw.setTop((int)((17d / 100 * height)));
views.get("button_cancel").vw.setLeft((int)((24d / 100 * width)));
views.get("button_cancel").vw.setWidth((int)((18d / 100 * width)));
views.get("button_cancel").vw.setHeight((int)((5d / 100 * height)));
views.get("panel_bg_msgbox").vw.setTop((int)((0d / 100 * height)));
views.get("panel_bg_msgbox").vw.setLeft((int)((0d / 100 * width)));
views.get("panel_bg_msgbox").vw.setWidth((int)((100d / 100 * width)));
views.get("panel_bg_msgbox").vw.setHeight((int)((100d / 100 * height)));
views.get("panel_msgbox").vw.setTop((int)((40d / 100 * height)));
views.get("panel_msgbox").vw.setLeft((int)((10d / 100 * width)));
views.get("panel_msgbox").vw.setWidth((int)((80d / 100 * width)));
views.get("panel_msgbox").vw.setHeight((int)((20d / 100 * height)));
views.get("panel_header_msgbox").vw.setTop((int)((0d / 100 * height)));
views.get("panel_header_msgbox").vw.setLeft((int)(0-(1d / 100 * width)));
views.get("panel_header_msgbox").vw.setWidth((int)((82d / 100 * width)));
views.get("panel_header_msgbox").vw.setHeight((int)((7d / 100 * height)));
views.get("label_header_logo").vw.setTop((int)((0d / 100 * height)));
views.get("label_header_logo").vw.setLeft((int)((2d / 100 * width)));
views.get("label_header_logo").vw.setWidth((int)((10d / 100 * width)));
views.get("label_header_logo").vw.setHeight((int)((7d / 100 * height)));
views.get("label_header_text").vw.setTop((int)((0d / 100 * height)));
views.get("label_header_text").vw.setLeft((int)((12d / 100 * width)));
views.get("label_header_text").vw.setWidth((int)((66d / 100 * width)));
views.get("label_header_text").vw.setHeight((int)((7d / 100 * height)));
views.get("label_msgbox1").vw.setTop((int)((8d / 100 * height)));
views.get("label_msgbox1").vw.setLeft((int)((3d / 100 * width)));
views.get("label_msgbox1").vw.setWidth((int)((74d / 100 * width)));
views.get("label_msgbox1").vw.setHeight((int)((4d / 100 * height)));
views.get("label_msgbox2").vw.setTop((int)((12d / 100 * height)));
views.get("label_msgbox2").vw.setLeft((int)((3d / 100 * width)));
views.get("label_msgbox2").vw.setWidth((int)((74d / 100 * width)));
views.get("label_msgbox2").vw.setHeight((int)((3d / 100 * height)));
views.get("pb_msgbox").vw.setTop((int)((17d / 100 * height)));
views.get("pb_msgbox").vw.setLeft((int)((2d / 100 * width)));
views.get("pb_msgbox").vw.setWidth((int)((76d / 100 * width)));
views.get("pb_msgbox").vw.setHeight((int)((2d / 100 * height)));

}
}